#!/bin/bash

mkdir -p build_logfile

if [ ! -z $1 ] ; then
#	time make $* 2>&1 | tee build_logfile/make_$(date +%d.%m.%Y_%H%M).log
	time make $* 2>&1 | tee build_logfile/make.log
else
	echo "Usage: makelog some_commands"
fi
