#! /bin/sh
#
# halt		Execute the halt command.
#
# Version:      @(#)halt  2.84-2  07-Jan-2002  miquels@cistron.nl
#

PATH=/sbin:/bin:/usr/sbin:/usr/bin

# See if we need to cut the power.
if test -x /etc/init.d/ups-monitor
then
	/etc/init.d/ups-monitor poweroff
fi

# Don't shut down drives if we're using RAID.
hddown="-h"
if grep -qs '^md.*active' /proc/mdstat
then
	hddown=""
fi

# halt depp stanby
mount -t ramfs ramfs /dev
mkdir -p /dev/dbox 
mknod /dev/dbox/vfd c 147 0 
/usr/sbin/vfdctl cleardisplay  #clear text in display

if [ `cat /etc/wakeup_time` != 0 ]; then 
     /usr/sbin/vfdctl standby 
fi

/usr/sbin/vfdctl deep         #halt display to deep standby

: exit 0
