#!/bin/sh

MODDIR=/lib/modules

insmod $MODDIR/vfd.ko       
echo "    Welcome     " > /dev/vfd

if [ -e /var/etc/.firstboot ]; then
   echo "WAIT 1 min" > /dev/vfd
   echo "WAIT 1 min"
   rm /var/etc/.firstboot
   touch /dev/.devfsd
fi

/etc/init.d/mountvirtfs start

if [ ! -e /var/etc/.firstboot ]; then

   insmod $MODDIR/e2_proc.ko

   # mme bug workaround
   /bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096
   /bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096
   # end mme bug wa
   echo "load a firmware"
   /bin/ustslave /dev/st231-1 /boot/audio.elf
   echo "load v firmware"
   /bin/ustslave /dev/st231-0 /boot/video.elf

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/autologin

   #used by fp_control! otherwise crash
   insmod $MODDIR/boxtype.ko

   echo "LOADING MODULES"   
   fp_control -c
   
   echo "init embxshell"
   insmod $MODDIR/embxshell.ko
   echo "init embxmailbox"
   insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:137:set2 ;
   echo "init embxshm"
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0xa4000000:0x10000000 ;
   echo "init mme_host"
   insmod $MODDIR/mme_host.ko transport0=shm

   echo "init AVS"
   insmod $MODDIR/avs.ko
   player=`cat /proc/stb/player/version`
   if [ $player=='player179' ]; then
      echo "init player 179"
   else
      echo "init player 131"
   fi

   echo "init stmfb"
   insmod $MODDIR/stmcore-display-stx7100.ko
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:8m:pal:yuv:yuv;# display1=720x576-16@50:1m:pal:cvbs;

   echo "init player"
   insmod $MODDIR/mmelog.ko
   insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER0;
   insmod $MODDIR/stmsysfs.ko
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/p2div64.ko
   insmod $MODDIR/stm_v4l2.ko
   insmod $MODDIR/pseudocard.ko
   if [ $player=='player179' ]; then
      insmod $MODDIR/stmvout.ko
      insmod $MODDIR/stmvbi.ko
   fi

   insmod $MODDIR/cx24116.ko
   insmod $MODDIR/cimax.ko
   if [ $player=='player179' ]; then
      insmod $MODDIR/pti.ko
      insmod $MODDIR/stm_monitor.ko
      insmod $MODDIR/stmsysfs.ko
      insmod $MODDIR/stmdvb.ko
   else
      insmod $MODDIR/pti.ko
      insmod $MODDIR/stmdvb.ko
      insmod $MODDIR/stm_monitor.ko
   fi
   insmod $MODDIR/player2.ko
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   insmod $MODDIR/silencegen.ko
   insmod $MODDIR/bpamem.ko

   echo "init lircd"
   mkdir -p /var/run/lirc
   /usr/bin/lircd

   echo "init frontpanel"
   insmod $MODDIR/simu_button.ko
   /bin/evremote2 &
   var=`cat /proc/boxtype`
   case "$var" in
   	0) echo "1W boxtype"
	   echo "B" > /dev/ttyAS1
           echo "B" > /dev/ttyAS1;;
  	1|3) echo "14W boxtype"
      	   insmod $MODDIR/button.ko
      	   insmod $MODDIR/led.ko;;
   	*) echo "unknown boxtype";;
   esac

   #DVD-PLAYER EXIT-TASTE LOAD OR EJECT DVD
   #mount /dev/sr0 /media/dvd
   #mount -t ext3 /dev/sda1 /hdd/movie

   /etc/init.d/portmap start
   /etc/init.d/vsftpd start
   /usr/sbin/inetd

   #timefix e2
   date -s "200901011200"

   stfbcontrol a 255

   echo "LOADING Enigma1" > /dev/vfd
   echo "LOADING Enigma1"

   until false
   do
      echo "starting Enigma1 ->"
      /usr/bin/enigma
      rtv=$?
      echo "neutrino ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "ERROR"
		   exit 1;;
		1) echo "1"
		   echo "SHUTDOWN"
		   exit 1;;
		2) echo "2"
		   echo "REBOOT"
		   exit 1;;
		3) echo "3"
		   echo "RESTART"
		   echo "0" > /proc/progress
		   showiframe -p /var/boot/bootlogo.mvi &;;
		*) echo "*"
		   echo "ERROR"
           exit 6;;
      esac
   done 
fi

#never reached
echo "REBOOT UFS910" > /dev/vfd
echo "REBOOT UFS910"
echo "reboot"
exit 0
