#!/bin/sh

   MODDIR=/lib/modules
   insmod $MODDIR/micom.ko

if [ -e /var/etc/.firstboot ]; then
   #fp_control does not work here
   echo "WAIT 1 min" >/dev/vfd
   echo "WAIT 1 min"
   rm /var/etc/.firstboot
   touch /dev/.devfsd
fi

/etc/init.d/mountvirtfs start

/etc/init.d/portmap start

insmod $MODDIR/e2_proc.ko

/etc/init.d/autofs start

if [ ! -e /var/etc/.firstboot ]; then

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   fp_control -c

   #green led on
   #fp_control -l 2 1

   #led brightness
   fp_control -led 80

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/autologin

   echo "init stmfb"
   insmod $MODDIR/stmcore-display-sti7111.ko
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:cvbs:yuv;# display1=720x576-16@50:1m:pal:cvbs;

   echo "LOADING MODULES"
   fp_control -t "LOADING MODULES"

   if [ ! -e /lib/firmware/audio.elf ]; then
      fp_control -t "FW MISSING!!!"
   fi

   echo "load video firmware"
   /bin/dd if=/dev/zero of=/dev/st231-0 bs=1024 count=4096
#   /bin/stslave -t st231.0 -R /lib/firmware/video.elf
   /bin/ustslave /dev/st231-0 /lib/firmware/video.elf

   echo "load audio firmware"
   /bin/dd if=/dev/zero of=/dev/st231-1 bs=1024 count=4096
#   /bin/stslave -t st231.1 -R /lib/firmware/audio.elf
   /bin/ustslave /dev/st231-1 /lib/firmware/audio.elf

   echo "init embx"
   insmod $MODDIR/embxshell.ko
   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
   insmod $MODDIR/mme_host.ko transport0=shm

   echo "init AVS"
   insmod $MODDIR/avs.ko type=stv6417

   echo "init player"
   insmod $MODDIR/mmelog.ko
   #there is no mpeg2hw on ufs912, will be handled by fw & copos
   #insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER0;
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/p2div64.ko
   insmod $MODDIR/stm_v4l2.ko
   insmod $MODDIR/stmvout.ko
   insmod $MODDIR/stmvbi.ko
   insmod $MODDIR/pseudocard.ko

   insmod $MODDIR/stv090x.ko
   insmod $MODDIR/ufs912_cic.ko
   insmod $MODDIR/pti.ko

   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/stmsysfs.ko
   insmod $MODDIR/stmdvb.ko
   insmod $MODDIR/player2.ko discardlateframe=0
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   insmod $MODDIR/silencegen.ko

   insmod $MODDIR/bpamem.ko

   echo "init frontpanel"

   #timefix
   date -s "200901011200"

#   echo "starting telnetd"
#   /usr/sbin/telnetd -l /bin/autologin
#   /etc/init.d/vsftpd start
   /usr/sbin/inetd

   NFS=$(grep -c 'nfs' /proc/cmdline)
   if [ "$NFS" -eq "1" ]; then
      echo "Booting from nfs, don't set network"
   else
      if [ -e /etc/network/interfaces ]; then
         ip addr flush eth0
         /etc/init.d/networking stop
         TEST=$(grep -c 'dhcp' /etc/network/interfaces)
         if [ "$TEST" -eq "1" ]; then
            echo dhcp
            /etc/init.d/udhcpc start
         fi
         /etc/init.d/networking start
      fi
   fi

   echo `ifconfig eth0 | sed -n '/inet addr/s/.*addr.\([^ ]*\) .*/\1/p'` > /dev/vfd

   echo "LOADING tvheadend"

   until false
   do
      echo "starting tvheadend ->"
      /usr/local/bin/tvheadend --http_port 80 -C
      rtv=$?
      echo "tvheadend ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "E2 ERROR"
      	   init 6;;
		1) echo "1"
		   echo "SHUTDOWN"
		   init 0;;
		2) echo "2"
		   echo "REBOOT"
		   init 6;;
		3) echo "3"
		   echo "E2 RESTART"
		   echo "0" > /proc/progress
		   showiframe -p /var/boot/bootlogo.mvi &;;
		*) echo "*"
		   echo "ERROR"
           init 6;;
      esac
   done
fi

#never reached

