#!/bin/sh
#Version 140727.1

echo "Fortis HS7110"

MODDIR=/lib/modules

echo "Init frontpanel"
insmod $MODDIR/nuvoton.ko paramDebug=0
insmod $MODDIR/simu_button.ko

if [ -e /var/etc/.firstboot ]; then
   echo "WAIT 1 min"
   rm /var/etc/.firstboot
   sleep 1
   touch /dev/.devfsd
else
   echo "LOAD 10"
fi

/etc/init.d/mountvirtfs start
/etc/init.d/portmap start

insmod $MODDIR/e2_proc.ko

# Start automounter with umount timeout of 5 seconds
insmod $MODDIR/autofs4.ko

/etc/init.d/autofs start

echo "Starting DEBUG Interface"
/etc/init.d/mountall start
/etc/init.d/hostname start

echo -n "Starting telnetd "
autologin=`cat /etc/enigma2/settings | grep systemoptions.autologin | cut -d "=" -f2`
if [ ! $autologin ]; then
   /usr/sbin/telnetd -l /bin/autologin
   echo "with autologin"
else
   /usr/sbin/telnetd -l /bin/login
   echo "with normal login"
fi

echo "Init stmfb (LOAD 9"
insmod $MODDIR/stmcore-display-sti7111.ko

if grep -q "config.av.videoport=Scart" /etc/enigma2/settings; then
  insmod $MODDIR/stmfb.ko display0=720x576i-32@50:15m:pal:rgb:rgb; #SCART
else
  insmod $MODDIR/stmfb.ko display0=1280x720-32@50:15m:pal:rgb:rgb; #HDMI
fi

echo "Loading modules"

if [ ! -e /boot/audio.elf ]; then
   echo "NO AUDIO FW!!!"
   echo "NOFW" > /dev/vfd
fi

echo "Load audio firmware (LOAD 8)"
echo "LOAD 8" > /dev/vfd
dtsdown=`cat /etc/enigma2/settings | grep systemoptions.dtsdownmix | cut -d "=" -f2`
if [ ! $dtsdown ] && [ -e /boot/audio_dts.elf ]; then
   /bin/ustslave /dev/st231-1 /boot/audio_dts.elf > /dev/null
else
   /bin/ustslave /dev/st231-1 /boot/audio.elf > /dev/null
fi

echo "Load video firmware (LOAD 7)"
echo "LD 7" > /dev/vfd
/bin/ustslave /dev/st231-0 /boot/video.elf > /dev/null

echo "Init embx (LOAD 6)"
insmod $MODDIR/embxshell.ko
insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
insmod $MODDIR/mme_host.ko transport0=shm

echo "Init AVS (LOAD 5)"
insmod $MODDIR/avs.ko type=avs_none

player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
echo "Init player $player (LOAD 4)"

insmod $MODDIR/mmelog.ko
insmod $MODDIR/ksound.ko
insmod $MODDIR/p2div64.ko
insmod $MODDIR/stm_v4l2.ko
if [ $player -gt 131 ]; then
   insmod $MODDIR/stmvout.ko
   insmod $MODDIR/stmvbi.ko
fi
insmod $MODDIR/pseudocard.ko

insmod $MODDIR/lnb.ko type=a8293
insmod $MODDIR/stv090x.ko paramDebug=0
insmod $MODDIR/hs7110.ko
if [ $player -gt 131 ]; then
   insmod $MODDIR/pti.ko
   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/stmsysfs.ko
   insmod $MODDIR/stmdvb.ko
else
   insmod $MODDIR/pti.ko
   insmod $MODDIR/stmdvb.ko
   insmod $MODDIR/stm_monitor.ko
fi

echo "LOAD 3" > /dev/vfd
insmod $MODDIR/player2.ko
insmod $MODDIR/sth264pp.ko
insmod $MODDIR/stmalloc.ko
insmod $MODDIR/platform.ko
insmod $MODDIR/silencegen.ko

insmod $MODDIR/smartcard.ko

#echo "Init HDMI-CEC"
#insmod $MODDIR/cec.ko activemode=1

insmod $MODDIR/bpamem.ko
mknod /dev/bpamem c 153 0

showiframe -p /boot/bootlogo.mvi &
stfbcontrol a 0

echo "Init lircd (LOAD 2)"
mknod /dev/rc c 147 1 
mknod /dev/lnb c 149 0

echo "Init smartcard cardreader"
mknod /dev/sci0 c 169 0

/bin/evremote2 10 140 &

stfbcontrol a 255

# Why is this done twice?
#/etc/init.d/mountall start
#/etc/init.d/hostname start

#echo "Starting telnetd"
#/usr/sbin/telnetd -l /bin/autologin

wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
   echo "No WLAN"
else
   insmod $MODDIR/$wlan.ko
   echo "$wlan WLAN"
fi

if [ -e $MODDIR/ntfs.ko ]; then
   insmod $MODDIR/ntfs.ko
fi

if [ -e $MODDIR/cifs.ko ]; then
   insmod $MODDIR/cifs.ko
fi

echo "LD 1" > /dev/vfd
/etc/init.d/vsftpd start
/usr/sbin/inetd

NFS=`grep -c nfs /proc/cmdline`
if [ "$NFS" -eq "1" ]; then
   echo "Booting from nfs, don't set network"
else
   if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      /etc/init.d/networking stop
      DHCP=`grep -c dhcp /etc/network/interfaces`
      if [ "$DHCP" -eq "1" ]; then
         echo "Starting DHCP"
         /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start
   fi
fi

# Do own extras
if [ -e /etc/ownscript.sh ]; then
   /etc/ownscript.sh &
fi

# Try and synchronise time
inettime=`cat /etc/enigma2/settings | grep systemoptions.inettime | cut -d "=" -f2`
if [ ! $inettime ] && [ -e /sbin/ntpdate ]; then
   echo "Set internet time"
#   (/sbin/ntpdate pl.pool.ntp.org; /bin/fp_control -s `date +"%H:%M:%S %d-%m-%Y"`) &
   (/sbin/ntpdate ntp.nasa.gov; /bin/fp_control -s `date +"%H:%M:%S %d-%m-%Y"`) &
else
   if [ -e /usr/sbin/time.sh ]; then
      echo "Use transponder time"
      /usr/sbin/time.sh &
   fi
fi

echo "Start Enigma2"
echo "LDE2" > /dev/vfd

until false
do
   echo "Entering e2 main loop"
   if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
      showiframe -p /usr/local/share/enigma2/backdrop.mvi
   fi
   /usr/local/bin/enigma2
   rtv=$?
   echo "e2 ended <- RTV: " $rtv
   case "$rtv" in
      0) echo "0"
         echo "E2 ERROR"
         init 6;;
      1) echo "1"
         echo "SHUTDOWN"
         init 0;;
      2) echo "2"
         echo "REBOOT"
         init 6;;
      3) echo "3"
         echo "E2 RESTART"
         echo "0" > /proc/progress
         showiframe -p /boot/bootlogo.mvi &;;
      *) echo "*"
         echo "ERROR"
         init 6;;
   esac
done 

#never reached
echo "REBOOT HS7110"
reboot -f
