#!/bin/sh

. /etc/profile
echo "[rcS] `date +'%d.%m.%Y %H:%M:%S'` start"
SYSDATE=`date +"%Y%m%d"`

read model < /etc/model

if [ -e /var/etc/.firstboot ]; then
/usr/bin/passwd root <<EOF
root
root
EOF
  rm /var/etc/.firstboot
fi

mkdir -p /dev/pts

echo "[rcS] starting mountall"
/etc/init.d/mountall start

if [ -e /var/backup_flash.tar.gz ]; then
	tar xvf /var/backup_flash.tar.gz -C /
	rm -f /var/backup_flash.tar.gz
fi

if [ -e /sys/class/net/lo ]; then
	/sbin/ifconfig lo up
fi
if [ -e /sys/class/net/eth0 ]; then
	/sbin/ifconfig eth0 up
fi
if [ -e /sys/class/net/eth1 ]; then
	/sbin/ifconfig eth1 up
fi
if [ -e /sys/class/net/sys0 ]; then
	/sbin/ifconfig sys0 up
fi

# load moduls from modules.extra ( kerneloptions )
[ -f /var/etc/modules.extra ] && eval `awk '{ if ($1) print "insmod /lib/modules/" $1 ".ko " $2,$3,$4,$5,$6,$7,$8,$9 "; "}' < /var/etc/modules.extra`

echo "[rcS] setup network"
NFS=$(grep -c nfs /proc/cmdline)
if [ "$NFS" -eq "1" ]; then
	echo "Booting from nfs, don't set network"
elif [ -e /var/tuxbox/config/.bootargs ]; then
	echo "using ip set via bootargs, don't reset network"
else
	if [ -e /etc/network/interfaces ]; then
		ip addr flush eth0
		/etc/init.d/networking stop
		#DHCP=$(grep -c dhcp /etc/network/interfaces)
		#if [ "$DHCP" -eq "1" ]; then
		#	echo "Starting dhcp"
		#	/etc/init.d/udhcpc start
		#fi
		/etc/init.d/networking start
	fi
fi
/sbin/ifconfig lo 127.0.0.1 up

# get net-time
(ntpd -n -q -p time.fu-berlin.de) &

/etc/init.d/hostname start
/etc/init.d/portmap start
/usr/sbin/inetd
# rpc.statd for nfs
/etc/init.d/nfs-common start

echo "[rcS] `date +'%d.%m.%Y %H:%M:%S'` load modules"

if [ ! -e /dev/brcm0 ]; then
	insmod /lib/modules/procmk.ko
	insmod /lib/modules/bcm_event.ko
	insmod /lib/modules/dvb_base.ko
	start-stop-daemon --start --quiet --exec /usr/bin/dvb_server -- &
	mknod -m a=rw /dev/brcm0 c 30 0
	start-stop-daemon --start --quiet --exec /usr/bin/init_client /lib/modules/dvb-bcm7444.ko /lib/modules/brcmfb.ko /lib/modules/wakeup_drv.ko -- &
fi

#insmod /lib/modules/fpga_directc.ko

while [ ! -c /dev/fb0 ]; do
	usleep 100000
done

echo 100 > /proc/stb/fp/oled_brightness
oled -tc "Booting... DDT"

/bin/initfb $(sed -n 's/osd_resolution=//p' /var/tuxbox/config/neutrino.conf)

echo "[rcS] starting mdev"
mdev -s

# set dummy time
NTPDATE=`date +"%Y%m%d"`
if [ "$SYSDATE" == "$NTPDATE" ];then
	date -s "2017-01-01 00:00"
	#date -s "200901011200"
	echo "no ntp-date"
	killall -9 ntpd
	rm -f /tmp/ntpd.pid
else
	echo "[rcS] ntp-date is set > `date +'%d.%m.%Y %H:%M'`"
	rm -f /tmp/ntpd.pid
fi


until false
do
	echo "[rcS] starting GUI ->"
	if [ -e /tmp/neutrino ]; then
		chmod 755 /tmp/neutrino
		/tmp/neutrino
	else
		/usr/bin/neutrino -v 0
	fi
	rtv=$?
	echo "GUI ended <- RTV: " $rtv
	case "$rtv" in
		0) echo "$rtv"
			echo "SHUTDOWN"
			init 0;;
		1) echo "$rtv"
			echo "REBOOT"
			oled -tc "REBOOT"
			init 6;;
		3) echo "$rtv"
			echo "RESTART"
			oled -tc "RESTART"
			sync;;
		*) echo "*"
			echo -e "\033[01;31mERROR: $rtv\033[00m"
			oled -tc "ERROR: $rtv"
			#init 6
			;;
	esac
done

#never reached
oled -tc "REBOOT $model"
echo "REBOOT $model"
reboot -f
