#!/bin/sh

MODDIR=/lib/modules

insmod $MODDIR/micom.ko paramDebug=50

if [ -e /var/etc/.firstboot ]; then
   rm /var/etc/.firstboot
   sleep 1
   echo "WAIT 3 min"
   echo "WAIT 3 min" >/dev/vfd
   touch /dev/.devfsd
fi

/etc/init.d/mountvirtfs start

if [ -e /dev/ttyAS1 ]; then 
   rm -f /dev/ttyAS1 
fi 

/etc/init.d/portmap start

insmod $MODDIR/e2_proc.ko

# start automounter with umount timeout of 5 seconds
insmod $MODDIR/autofs4.ko
/usr/sbin/automount --timeout=5 /autofs file /etc/auto.usb

if [ ! -e /var/etc/.firstboot ]; then
   echo "LOADING MODULES" > /dev/vfd
   echo "LOADING MODULES"   

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   fp_control -c

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/autologin

   echo "init stmfb"
   insmod $MODDIR/stmcore-display-stx7109c3.ko
   /bin/eeprom tvmode
   TVMODE=$?
   case "$TVMODE" in
	0) echo "SD-PAL"
  	   insmod $MODDIR/stmfb.ko display0=720x576-32@50:12m:pal:yuv:yuv;;
	1) echo "SD-NTSC"
	   insmod $MODDIR/stmfb.ko display0=720x480-32@60:12m:ntsc-m:yuv:yuv;;
	2) echo "720P-50"
	   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:yuv:yuv;;
	3) echo "720P-60"
	   insmod $MODDIR/stmfb.ko display0=1280x720-32@60:12m:ntsc-m:yuv:yuv;;
	4) echo "1080I-50"
	   insmod $MODDIR/stmfb.ko display0=1920x1080-32@50i:12m:pal:yuv:yuv;;
	5) echo "1080I-60"
	   insmod $MODDIR/stmfb.ko display0=1920x1080-32@60i:12m:ntsc-m:yuv:yuv;;
	*) echo "Use default SD-PAL"
	   insmod $MODDIR/stmfb.ko display0=720x576-32@50:12m:pal:yuv:yuv;;
   esac

   echo "init AVS"
   insmod $MODDIR/avs.ko type=stv6418

   echo "load a/v firmware"
   /bin/ustslave /dev/st231-1 /boot/audio.elf
   /bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   insmod $MODDIR/embxshell.ko
   insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0xa4000000:0x10000000 ;
   insmod $MODDIR/mme_host.ko transport0=shm

   echo "init player"
   insmod $MODDIR/mmelog.ko
   insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER1;
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/p2div64.ko
   insmod $MODDIR/stm_v4l2.ko
   insmod $MODDIR/pseudocard.ko

   insmod $MODDIR/frontend_platform.ko
   insmod $MODDIR/socket.ko
   insmod $MODDIR/lnbh221.ko
   insmod $MODDIR/lnb_pio.ko

   if [ -f $MODDIR/dvb-pll.ko ]; then
       insmod $MODDIR/dvb-pll.ko
   fi

   if [ -f $MODDIR/cx24116.ko ]; then
       insmod $MODDIR/cx24116.ko
   fi

   if [ -f $MODDIR/tda10023.ko ]; then
       insmod $MODDIR/tda10023.ko
   fi

   if [ -f $MODDIR/zl10353.ko ]; then
       insmod $MODDIR/zl10353.ko
   fi

   if [ -f $MODDIR/stv090x.ko ]; then
       insmod $MODDIR/stv090x.ko
   fi

   if [ -f $MODDIR/stv0288.ko ]; then
       insmod $MODDIR/stv0288.ko
   fi

   insmod $MODDIR/starci.ko

   # Full feature pti
   insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
   if [ $?=='2' ]; then
      # Simple pti
      insmod $MODDIR/pti.ko
   fi
   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/stmsysfs.ko
   insmod $MODDIR/stmdvb.ko

   insmod $MODDIR/player2.ko
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   insmod $MODDIR/silencegen.ko 

   showiframe -p /var/boot/bootlogo.mvi &
   stfbcontrol a 0

   echo "init frontpanel"
   insmod $MODDIR/simu_button.ko

   mknod /dev/rc c 147 1 

   #params:
   #period
   #delay
   /bin/evremote2 10 140 &

   stfbcontrol a 255

   /etc/init.d/mountall start

   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/autologin
   /etc/init.d/vsftpd start
   /usr/sbin/inetd

   NFS=`grep -c nfs /proc/cmdline`
   if [ "$NFS" -eq "1" ]; then 
      echo "Booting from nfs, don't set network" 
   else 
      if [ -e /etc/network/interfaces ]; then 
	 ip addr flush eth0 
	 /etc/init.d/networking stop 
	 DHCP=`grep -c dhcp /etc/network/interfaces`
	 if [ "$DHCP" -eq "1" ]; then 
	    echo "Starting dhcp"
            /etc/init.d/udhcpc start 
	 fi 
	 /etc/init.d/networking start 
      fi 
   fi

   echo "LOADING e2" > /dev/vfd
   echo "LOADING e2"

   until false
   do
      echo "starting e2->"
      /usr/local/bin/enigma2
      rtv=$?
      echo "e2 ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "E2 ERROR"
      	   init 6;;
		1) echo "1"
		   echo "SHUTDOWN"
		   init 0;;
		2) echo "2"
		   echo "REBOOT"
		   fp_control -r 00:00:00 01.01.1980;;
		3) echo "3"
		   echo "E2 RESTART"
		   echo "0" > /proc/progress
		   showiframe -p /var/boot/bootlogo.mvi &;;
		*) echo "*"
		   echo "ERROR"
		   fp_control -r 00:00:00 01.01.1980;;
      esac
   done 
fi

#never reached

