#!/bin/sh

MODDIR=/lib/modules
insmod $MODDIR/sagemcomtype.ko
boxtype=`cat /proc/boxtype`

if [ $boxtype == 'uhd88' ]; then
  echo "Init LED"
  insmod $MODDIR/front_led.ko
else
  echo "Init VFD"
  insmod $MODDIR/front_vfd.ko
fi

if [ -e /var/etc/.firstboot ]; then
   echo "WAIT 1st start" >/dev/vfd
   echo "WAIT 1st start"
   rm /var/etc/.firstboot
   sleep 1
   touch /dev/.devfsd
fi

/etc/init.d/mountvirtfs start
/etc/init.d/portmap start

# start automounter with umount timeout of 5 seconds
if [ -e $MODDIR/autofs4.ko ]; then
	insmod $MODDIR/autofs4.ko
	/usr/sbin/automount --timeout=5 /autofs file /etc/auto.usb
fi

if [ ! -e /var/etc/.firstboot ]; then
   
   insmod $MODDIR/e2_proc.ko

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/login

   echo "init stmfb"
   insmod $MODDIR/stmcore-display-sti7105.ko
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:16m:pal:yuv:yuv;

   echo "LOADING MODULES"   
   echo "LOADING MODULES" >/dev/vfd

   if [ ! -e /boot/audio.elf ]; then
      echo "FW MISSING!!!"
   fi

   echo "load a firmware"
   /bin/ustslave /dev/st231-1 /boot/audio.elf

   echo "load v firmware"
   /bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   insmod $MODDIR/embxshell.ko
   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
   insmod $MODDIR/mme_host.ko transport0=shm

	echo "init AVS"
	insmod $MODDIR/avs.ko type=ak4708

	echo "init player 191"
	insmod $MODDIR/mmelog.ko
	insmod $MODDIR/ksound.ko
	insmod $MODDIR/p2div64.ko
	insmod $MODDIR/stm_v4l2.ko
	insmod $MODDIR/pseudocard.ko

	if [ $boxtype == 'uhd88' ]; then
		insmod $MODDIR/fe-core.ko box_type=1
	else
		insmod $MODDIR/fe-core.ko box_type=0
	fi
    
	echo "init drivers"
	insmod $MODDIR/pti.ko
	insmod $MODDIR/stm_monitor.ko
	insmod $MODDIR/stmsysfs.ko
	insmod $MODDIR/stmdvb.ko
    insmod $MODDIR/player2.ko discardlateframe=0
	insmod $MODDIR/sth264pp.ko
	insmod $MODDIR/stmalloc.ko
	insmod $MODDIR/platform.ko

   if [ -e $MODDIR/bpamem.ko ]; then
        insmod $MODDIR/bpamem.ko
        mknod /dev/bpamem0 c 153 0
   fi

   showiframe -p /boot/bootlogo.mvi &
   stfbcontrol a 0

   echo "init frontpanel"
   insmod $MODDIR/simu_button.ko

   echo "init lircd"
      /usr/bin/lircd

   mknod /dev/rc c 147 1

      /bin/evremote2 &

   echo "starting vsftpd"
   /etc/init.d/vsftpd start
   /usr/sbin/inetd

   #timefix e2 in format MMDDhhmmYYYYY.ss
   date -s "121220001970"

   stfbcontrol a 255

   until false
   do
      echo "starting e2->"
      /usr/local/bin/enigma2
      rtv=$?
      echo "e2 ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "E2 ERROR" > /dev/vfd
		   sync
		   init 6;;
		1) echo "1"
		   echo "SHUTDOWN" > /dev/vfd
		   sync
		   init 0
		   umount -a;;
		2) echo "2"
		   echo "REBOOT" > /dev/vfd
		   sync
		   init 6;;
		3) echo "3"
		   echo "E2 RESTART" > /dev/vfd
		   echo "0" > /proc/progress
		   showiframe -p /boot/bootlogo.mvi &;;
		*) echo "*"
		   echo "ERROR" > /dev/vfd
		   sync
		   echo "0" > /proc/progress
		   showiframe -p /boot/bootlogo.mvi &;;
      esac
   done
  fi
 fi
fi

#never reached
echo "REBOOT" > /dev/vfd
echo "REBOOT"
sync
reboot

