#!/bin/sh

. /etc/profile
echo "[rcS] `date +'%d.%m.%Y %H:%M:%S'` start"
SYSDATE=`date +"%Y%m%d"`

read model < /etc/model

if [ -e /var/etc/.firstboot ]; then
/usr/bin/passwd root <<EOF
root
root
EOF
  rm /var/etc/.firstboot
fi

mkdir -p /dev/pts

echo "[rcS] starting mountall"
/etc/init.d/mountall start

if [ -e /var/backup_flash.tar.gz ]; then
	tar xvf /var/backup_flash.tar.gz -C /
	rm -f /var/backup_flash.tar.gz
fi

echo "[rcS] add mmcblks in /dev/block"
/etc/init.d/mmcblk-by-name

# for start from power off
/etc/mdev/ttyUSB-check.sh

# load moduls from modules.extra ( kerneloptions )
[ -f /var/etc/modules.extra ] && eval `awk '{ if ($1) print "insmod /lib/modules/" $1 ".ko " $2,$3,$4,$5,$6,$7,$8,$9 "; "}' < /var/etc/modules.extra`

echo "[rcS] setup network"
NFS=$(grep -c nfs /proc/cmdline)
if [ "$NFS" -eq "1" ]; then
	echo "Booting from nfs, don't set network"
elif [ -e /var/tuxbox/config/.bootargs ]; then
	echo "using ip set via bootargs, don't reset network"
else
	if [ -e /etc/network/interfaces ]; then
		ip addr flush eth0
		/etc/init.d/networking stop
		#DHCP=$(grep -c dhcp /etc/network/interfaces)
		#if [ "$DHCP" -eq "1" ]; then
		#	echo "Starting dhcp"
		#	/etc/init.d/udhcpc start
		#fi
		/etc/init.d/networking start
	fi
fi
/sbin/ifconfig lo 127.0.0.1 up

# get net-time
(ntpd -n -q -p time.fu-berlin.de) &

/etc/init.d/hostname start
/etc/init.d/portmap start
/usr/sbin/inetd
# rpc.statd for nfs
/etc/init.d/nfs-common start

echo "[rcS] check boxmode"
cat /proc/cmdline | grep -q 'boxmode=12'
[ "$?" == "0" ] && BOXMODE=12 || BOXMODE=1
if [ ! -e /var/tuxbox/plugins/stb-startup.conf ]; then
	[ "$BOXMODE" == "12" ] && echo "boxmode_12=1" > /var/tuxbox/plugins/stb-startup.conf || echo "boxmode_12=0" > /var/tuxbox/plugins/stb-startup.conf
fi
echo "[rcS] boxmode=$BOXMODE"

echo "[rcS] `date +'%d.%m.%Y %H:%M:%S'` load modules"
insmod /lib/modules/hd51_1.ko
insmod /lib/modules/hd51_2.ko
insmod /lib/modules/hd51_3.ko
insmod /lib/modules/hd51_4.ko boxmode=$BOXMODE

echo "Booting... DDT" > /dev/dbox/oled0

echo "[rcS] starting mdev"
mdev -s

# set dummy time
NTPDATE=`date +"%Y%m%d"`
if [ "$SYSDATE" == "$NTPDATE" ];then
	date -s "2017-01-01 00:00"
	#date -s "200901011200"
	echo "no ntp-date"
	killall -9 ntpd
	rm -f /tmp/ntpd.pid
else
	echo "[rcS] ntp-date is set > `date +'%d.%m.%Y %H:%M'`"
	rm -f /tmp/ntpd.pid
fi


until false
do
	echo "[rcS] starting GUI ->"
	if [ -e /tmp/neutrino ]; then
		chmod 755 /tmp/neutrino
		/tmp/neutrino
	else
		/usr/bin/neutrino -v 0
	fi
	rtv=$?
	echo "GUI ended <- RTV: " $rtv
	case "$rtv" in
		0) echo "$rtv"
			echo "SHUTDOWN"
			echo "SHUTDOWN" > /dev/dbox/oled0
			init 0
			sleep 20
			;;
		1) echo "$rtv"
			echo "REBOOT"
			echo "REBOOT" > /dev/dbox/oled0
			init 6
			sleep 20
			;;
		3) echo "$rtv"
			echo "RESTART"
			echo "RESTART" > /dev/dbox/oled0
			sync
			;;
		*) echo "*"
			echo -e "\033[01;31mERROR: $rtv\033[00m"
			echo "ERROR: $rtv" > /dev/dbox/oled0
			#init 6
			#sleep 20
			;;
	esac
done
echo "      *-*       " > /dev/dbox/oled0

#never reached
echo "REBOOT $model" > /dev/dbox/oled0
echo "REBOOT $model"
reboot -f
