#!/bin/sh

MODDIR=/lib/modules

insmod $MODDIR/micom.ko
echo "init frontpanel"
insmod $MODDIR/simu_button.ko

if [ -e /var/etc/.firstboot ]; then
   #fp_control does not work here
   echo "WAIT 1 min" >/dev/vfd
   echo "WAIT 1 min"
   rm /var/etc/.firstboot
   touch /dev/.devfsd
fi

echo "Booting" > /dev/vfd

/etc/init.d/mountvirtfs start

/etc/init.d/portmap start

insmod $MODDIR/e2_proc.ko

/etc/init.d/autofs start

if [ ! -e /var/etc/.firstboot ]; then

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/autologin

   echo "init stmfb"
   insmod $MODDIR/stmcore-display-sti7111.ko
   if  grep -q "config.av.videoport=HDMI" /etc/enigma2/settings; then
         insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:yuv:yuv;
        echo "VIDEO:scart"
        VIDEO=scart
   else
        insmod $MODDIR/stmfb.ko display0=720x576-32@50i:12m:pal:yuv:rgb;
        echo "VIDEO:hdmi_component"
        VIDEO=hdmi_component
    fi

   echo "LOADING MODULES"   

   if [ ! -e /boot/audio.elf ]; then
      echo "FW MISSING!!!"
   fi

   echo "load audio firmware"
   /bin/ustslave /dev/st231-1 /boot/audio.elf
   echo "load video firmware"
   /bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   insmod $MODDIR/embxshell.ko
   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
   insmod $MODDIR/mme_host.ko transport0=shm

   echo "init AVS"
   insmod $MODDIR/avs.ko type=stv6419

   echo "init player 191"
   insmod $MODDIR/mmelog.ko
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/p2div64.ko
   insmod $MODDIR/stm_v4l2.ko
   insmod $MODDIR/stmvout.ko
   insmod $MODDIR/stmvbi.ko
   insmod $MODDIR/pseudocard.ko

   insmod $MODDIR/stv090x.ko
   insmod $MODDIR/starci.ko
   insmod $MODDIR/pti.ko
   insmod $MODDIR/stm_monitor.ko
   insmod $MODDIR/stmsysfs.ko
   insmod $MODDIR/stmdvb.ko
   insmod $MODDIR/player2.ko discardlateframe=0
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   insmod $MODDIR/silencegen.ko

   insmod $MODDIR/bpamem.ko
   mknod /dev/bpamem c 153 0


    showiframe -p /boot/bootlogo.mvi &
   stfbcontrol a 0

   insmod $MODDIR/smartcard.ko
   mknod /dev/sci0 c 169 0

   /bin/evremote2 &

   /etc/init.d/mountall start

   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/autologin
   /etc/init.d/vsftpd start
   /usr/sbin/inetd

   /etc/init.d/network start &

   echo "LOADING e2"
   echo "LOADING e2" > /dev/vfd

   stfbcontrol a 255

  # /etc/init.d/fixdate.sh

  # /etc/init.d/softcam start &

   until false
   do
      echo "starting e2->"
      /usr/local/bin/enigma2
      rtv=$?
      echo "e2 ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "E2 ERROR"
      	   init 6;;
		1) echo "1"
		   echo "SHUTDOWN"
		   init 0;;
		2) echo "2"
		   echo "REBOOT"
		   init 6;;
		3) echo "3"
		   echo "E2 RESTART"
		   echo "0" > /proc/progress
		   showiframe -p /boot/bootlogo.mvi &;;
		*) echo "*"
		   echo "ERROR"
           init 6;;
      esac
   done 
fi
