#!/bin/sh
#Version 140916.1

echo "[rcS] Start"
echo "Fortis HS7819 Enigma2"

MODDIR=/lib/modules

echo "[rcS] Init frontpanel"
if [ ! -e /dev/vfd ]; then
   mknod -m 0660 /dev/vfd c 147 0
fi
insmod $MODDIR/nuvoton.ko paramDebug=0
insmod $MODDIR/simu_button.ko

if [ -e /var/etc/.firstboot ]; then
   echo "1min" > /dev/vfd
   echo "[rcS] WAIT 1 minute"
   rm /var/etc/.firstboot
   sleep 1
   touch /dev/.devfsd
else
   echo "LD10" > /dev/vfd
   echo "LOAD 10"
fi

/etc/init.d/mountvirtfs start

insmod $MODDIR/e2_proc.ko

echo "[rcS] Starting automounter"
# Start automounter with umount timeout of 5 seconds
if [ -e $MODDIR/autofs4.ko ]; then
   insmod $MODDIR/autofs4.ko
fi
/etc/init.d/autofs start

echo "Starting DEBUG Interface"
/etc/init.d/mountall start
/etc/init.d/hostname start

echo -n "Starting telnetd "
autologin=`cat /etc/enigma2/settings | grep systemoptions.autologin | cut -d "=" -f2`
if [ ! $autologin ]; then
   /usr/sbin/telnetd -l /bin/autologin
   echo "with autologin"
else
   /usr/sbin/telnetd -l /bin/login
   echo "with normal login"
fi

echo "[rcS] Init stmfb (LOAD 9)"
echo "LD 9" > /dev/vfd
insmod $MODDIR/stmcore-display-sti7111.ko

if grep -q "config.av.videoport=Scart" /etc/enigma2/settings; then
   insmod $MODDIR/stmfb.ko display0=720x576i-32@50:12m:pal:rgb:rgb; #SCART
else
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:rgb:rgb; #HDMI
fi

echo "[rcS] Loading modules"

if [ ! -e /boot/audio.elf ] || [ ! -e /boot/video.elf ]; then
   echo "[rcS] Firmware(s) missing!"
   echo "NOFW" > /dev/vfd
fi

echo "[rcS] Load video firmware (LOAD 8)"
echo "LD 8" > /dev/vfd
/bin/ustslave /dev/st231-0 /boot/video.elf

echo "[rcS] Load audio firmware (LOAD 7)"
echo "LD 7" > /dev/vfd
dtsdown=`cat /etc/enigma2/settings | grep systemoptions.dtsdownmix | cut -d "=" -f2`
if [ ! $dtsdown ] && [ -e /boot/audio_dts.elf ]; then
   /bin/ustslave /dev/st231-1 /boot/audio_dts.elf
else
   /bin/ustslave /dev/st231-1 /boot/audio.elf
fi

echo "[rcS] Init embx (LOAD 6)"
echo "LD 6" > /dev/vfd
insmod $MODDIR/embxshell.ko
insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
insmod $MODDIR/mme_host.ko transport0=shm

echo "[rcS] Init AVS (LOAD 5)"
echo "LD 5" > /dev/vfd
insmod $MODDIR/avs.ko type=avs_pio

echo "[rcS] Init player (LOAD 4)"
echo "LD 4" > /dev/vfd
insmod $MODDIR/mmelog.ko
insmod $MODDIR/ksound.ko
insmod $MODDIR/p2div64.ko
insmod $MODDIR/stm_v4l2.ko

insmod $MODDIR/pseudocard.ko

echo "[rcS] Init frontend"
insmod $MODDIR/lnb.ko type=a8293
insmod $MODDIR/stv090x.ko paramDebug=0
mknod /dev/lnb c 149 0

echo "[rcS] Init CI & cardreader"
insmod $MODDIR/starci.ko
insmod $MODDIR/smartcard.ko

insmod $MODDIR/pti.ko
insmod $MODDIR/stm_monitor.ko
insmod $MODDIR/stmsysfs.ko
insmod $MODDIR/stmdvb.ko

echo "[rcS] Init player2 (LOAD 3)"
echo "LD 3" > /dev/vfd
insmod $MODDIR/player2.ko
insmod $MODDIR/sth264pp.ko
insmod $MODDIR/stmalloc.ko
insmod $MODDIR/platform.ko
insmod $MODDIR/silencegen.ko

insmod $MODDIR/bpamem.ko
mknod /dev/bpamem c 153 0

echo "[rcS] Init HDMI-CEC"
if [ -e $MODDIR/cec.ko ];then
   insmod $MODDIR/cec.ko activemode=1
fi

if [ -e $MODDIR/exportfs.ko ]; then
   insmod $MODDIR/exportfs.ko
fi
if [ -e $MODDIR/cifs.ko ]; then
   insmod $MODDIR/cifs.ko
fi
if [ -e $MODDIR/ntfs.ko ]; then
   insmod $MODDIR/ntfs.ko
fi
if [ -e $MODDIR/tun.ko ]; then
   insmod $MODDIR/tun.ko
fi
if [ -e $MODDIR/usbserial.ko ]; then
   insmod $MODDIR/usbserial.ko
fi
if [ -e $MODDIR/ftdi.ko ]; then
   insmod $MODDIR/ftdi.ko
fi
if [ -e $MODDIR/pl2303.ko ]; then
   insmod $MODDIR/pl2303.ko
fi

showiframe -p /boot/bootlogo.mvi &
stfbcontrol a 0

echo "[rcS] Init remote control (LOAD 2)"
echo "LD 2" > /dev/vfd
/bin/evremote2 10 140 &

stfbcontrol a 255

echo -n "[rcS] Init WLAN: "
wlan=`cat /etc/enigma2/settings | grep systemoptions.wlan | cut -d "=" -f2`
if [ ! $wlan ] || [ ! -e $MODDIR/$wlan.ko ]; then
   echo "None."
else
   insmod $MODDIR/$wlan.ko
   echo "$wlan"
fi

echo "[rcS] Init portmap & ftp (LOAD 1)"
echo "LD 1" > /dev/vfd
/etc/init.d/portmap start
/etc/init.d/vsftpd start
/usr/sbin/inetd

NFS=`grep -c nfs /proc/cmdline`
if [ "$NFS" -eq "1" ]; then
   echo "[rcS] Booting from nfs, don't set network"
else
   if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      /etc/init.d/networking stop
      DHCP=`grep -c dhcp /etc/network/interfaces`
      if [ "$DHCP" -eq "1" ]; then
         echo "[rcS] Starting DHCP"
         /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start
   fi
fi

# Handle SWAPPART and RECORD labels and USB devices
if [ -e /usr/sbin/amount.sh ]; then
   (sleep 20; /usr/sbin/amount.sh) &
fi

# inadyn
inadyn=`cat /etc/enigma2/settings | grep systemoptions.inadyn | cut -d "=" -f2`
if [ ! $inadyn ] ||  [ ! -e /usr/bin/inadyn ]; then
   echo "[rcS] No inadyn"
else
   if [ -e /usr/bin/inadyn ]; then
      /usr/bin/inadyn &
   fi
fi

# OpenSSh daemon
openssh=`cat /etc/enigma2/settings | grep systemoptions.openssh | cut -d "=" -f2`
if [ ! $openssh ] || [ ! -e /etc/init.d/sshd ]; then
   echo "[rcS] No OpenSSH"
else
   if [ -e /etc/init.d/sshd ]; then
      (sleep 30; /etc/init.d/sshd start) &
   fi
fi

# Enable PKT plugins
if [ ! -e /tmp/reference.dat ] && [ -e /var/bin/reference.dat ]; then
   cp /var/bin/reference.dat /tmp
fi

# Do own extras
if [ -e /etc/ownscript.sh ]; then
   /etc/ownscript.sh &
fi

#timefix e2
date -s "201409011200"
# Try and synchronise time
inettime=`cat /etc/enigma2/settings | grep systemoptions.inettime | cut -d "=" -f2`
if [ ! $inettime ] && [ -e /sbin/ntpdate ]; then
   echo "[rcS] Set internet time"
   (/sbin/ntpdate nl.pool.ntp.org; /bin/fp_control -s `date +"%H:%M:%S %d-%m-%Y"`) &
else
   if [ -e /usr/sbin/time.sh ]; then
      echo "[rcS] Use transponder time"
      /usr/sbin/time.sh &
   fi
fi

echo "[rcS] Loading OpenPLi"
echo "LDE2" > /dev/vfd

until false
do
   echo "[rcS] Entering e2 main loop"
   if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
      showiframe -p /usr/local/share/enigma2/backdrop.mvi
   fi
   /usr/local/bin/enigma2
   rtv=$?
   echo "[rcS] e2 ended <- return value: " $rtv
   case "$rtv" in
      0) echo "E2 ERROR"
         echo "E2ER" > /dev/vfd
         init 6;;
      1) echo "SHUTDOWN"
         echo "Shdn" > /dev/vfd
         init 0;;
      2) echo "REBOOT"
         echo "rebt" > /dev/vfd
         init 6;;
      3) echo "RESTART GUI"
         echo "E2rS" > /dev/vfd
         echo "0" > /proc/progress
         if [ -e /usr/local/share/enigma2/backdrop.mvi ]; then
            showiframe -p /usr/local/share/enigma2/backdrop.mvi &
         else
            showiframe -p /boot/bootlogo.mvi &
         fi
         echo -n " ";;
      *) echo "ERROR"
         echo "ERR " > /dev/vfd
         init 6;;
   esac
done

#never reached
echo "rebt" > /dev/vfd
echo "REBOOT HS7819"
reboot -f
