#!/bin/sh

MODDIR=/lib/modules
insmod $MODDIR/micom.ko paramDebug=0

if [ -e /var/etc/.firstboot ]; then
   # fp_control does not work here
  echo "WAIT 1 min" >/dev/vfd
  echo "WAIT 1 min"
   rm /var/etc/.firstboot
   touch /dev/.devfsd
fi

/etc/init.d/mountvirtfs start

/etc/init.d/portmap start

insmod $MODDIR/e2_proc.ko

if [ ! -e /var/etc/.firstboot ]; then

   echo "Starting DEBUG Interface"
   /etc/init.d/mountall start
   /etc/init.d/hostname start

   NFS=`grep -c nfs /proc/cmdline`
   if [ "$NFS" -eq "1" ]; then
      # We can not correct the mac from userspace if we are booting from nfsroot
      echo "Booting from nfs, don't set network"
   else
      HWADDR=`strings /dev/mtdblock2 | tail -n 1`
      ifconfig eth0 down
      ifconfig eth0 hw ether ${HWADDR}
      ifconfig eth0 up
   fi

   fp_control -c

   #green led on
   fp_control -l 2 1
   #led brightness
   fp_control -led 80

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/autologin

   echo "init stmfb"
   insmod $MODDIR/stmcore-display-sti7105.ko
   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:cvbs:yuv;# display1=720x576-16@50:8m:pal:cvbs;

   echo "LOADING MODULES"
   fp_control -t "LOADING MODULES"

   if [ ! -e /lib/firmware/audio.elf ]; then
      fp_control -t "FW MISSING!!!"
   fi

   echo "load a firmware"
   /bin/ustslave /dev/st231-1 /boot/audio.elf
   echo "load v firmware"
   /bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   insmod $MODDIR/embxshell.ko
   insmod $MODDIR/embxmailbox.ko mailbox0=0xfe211000:136:set2 mailbox1=0xfe212000:0 ;
   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0x40000000:0x10000000 ;
   insmod $MODDIR/mme_host.ko transport0=shm

   echo "init AVS"
   insmod $MODDIR/avs.ko type=stv6417

   player=`cat /proc/stb/player/version`
   if [ $player=='player191' ]; then
      echo "init player 191"
   elif [ $player=='player179' ]; then
      echo "init player 179"
   else
      echo "init player 131"
   fi
   insmod $MODDIR/mmelog.ko
   insmod $MODDIR/ksound.ko
   insmod $MODDIR/p2div64.ko
   insmod $MODDIR/stm_v4l2.ko
   insmod $MODDIR/pseudocard.ko

   insmod $MODDIR/frontend_platform.ko
   insmod $MODDIR/socket.ko
   insmod $MODDIR/lnbh221.ko
   insmod $MODDIR/lnb_pio.ko
   insmod $MODDIR/lnb_a8293.ko
   insmod $MODDIR/avl6222.ko
   insmod $MODDIR/ufs913_cic.ko
   if [ $player=='player191' ]; then
      # Full feature pti
      insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
      if [ $?=='2' ]; then
         # Simple pti
         insmod $MODDIR/pti.ko
      fi
      insmod $MODDIR/stm_monitor.ko
      insmod $MODDIR/stmsysfs.ko
      insmod $MODDIR/stmdvb.ko
   elif [ $player=='player179' ]; then
      # Full feature pti
      insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
      if [ $?=='2' ]; then
         # Simple pti
         insmod $MODDIR/pti.ko
      fi
      insmod $MODDIR/stm_monitor.ko
      insmod $MODDIR/stmsysfs.ko
      insmod $MODDIR/stmdvb.ko
   else
      insmod $MODDIR/pti.ko
      insmod $MODDIR/stmdvb.ko
      insmod $MODDIR/stm_monitor.ko
   fi
   insmod $MODDIR/player2.ko
   insmod $MODDIR/sth264pp.ko
   insmod $MODDIR/stmalloc.ko
   insmod $MODDIR/platform.ko
   insmod $MODDIR/silencegen.ko

   insmod $MODDIR/bpamem.ko

   # timefix e2
   # date -s "121220001970"

   /etc/init.d/mountall start

   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/autologin
   /etc/init.d/vsftpd start
   /usr/sbin/inetd

   /etc/init.d/network start &

   echo `ifconfig eth0 | sed -n '/inet addr/s/.*addr.\([^ ]*\) .*/\1/p'` > /dev/vfd

   echo "LOADING tvheadend"

   stfbcontrol a 255

   until false
   do
      echo "starting tvheadend ->"
      /usr/local/bin/tvheadend --http_port 80 -C
      rtv=$?
      echo "tvheadend ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "SHUTDOWN"
		   init 0;;
		1) echo "1"
		   echo "REBOOT"
		   init 6;;
		*) echo "*"
		   echo "ERROR"
		   init 6;;
      esac
   done
fi

#never reached
echo "REBOOT UFS913" > /dev/vfd
echo "REBOOT UFS913"
init 6
