#!/bin/sh

start()
{
  echo "[makedev] Starting makedev..."
  # Check if started on target or on host
  MACHINE=`uname -m`
  if [ $MACHINE == "sh4" ]; then
    MAKEDEV="/sbin/MAKEDEV -p /etc/passwd -g /etc/group"
    HOST=`cat /etc/hostname`
  else
    # Expecting to be in /dev
    if [ ! -e ../etc/passwd ] || [ ! -e ../etc/group ]; then
	MAKEDEV="../sbin/MAKEDEV -p ../var/etc/passwd -g ../var/etc/group"
	HOST=`cat ../var/etc/hostname`
    else
	MAKEDEV="../sbin/MAKEDEV -p ../etc/passwd -g ../etc/group"
	HOST=`cat ../etc/hostname`
    fi
  fi

  # Decide if we have CI and/or TWIN/TRIPLET
  CI="No"
  TUNER="1"
  for TARGET in cuberevo-9500hd cuberevo-mini2 cuberevo-mini cuberevo cuberevo-3000hd ufs922 ufs912 ufs913 ufc960 fortis atevio7500 octagon1008 hs7110 hs7810a hs7119 hs7819 ufs910 hl101 Edision-v1 Edision-v2 hs5101 tf7700 ipbox9900; do
    if [ ${HOST} == ${TARGET} ]; then
      CI="Yes"
      break
    fi
  done

  for TARGET in cuberevo-9500hd cuberevo ufs922 ufs913 fortis atevio7500 Adb_Box Edision-v1 tf7700 ipbox9900; do
    if [ ${HOST} == ${TARGET} ]; then
      TUNER="2"
      break
    fi
  done

  for TARGET in spark7162; do
    if [ ${HOST} == ${TARGET} ]; then
      TUNER="3"
      break
    fi
  done

  # Decide if we support HDMI CEC
  HDMI_CEC="No"
  for TARGET in atevio7500 hs7110 hs7810a hs7119 hs7819 spark spark7162 ufs912 ufs913; do
    if [ ${HOST} == ${TARGET} ]; then
      HDMI_CEC="Yes"
      break
    fi
  done

  echo " CI-slot(s) : ${CI}"
  echo " Tuners     : ${TUNER}"
  echo " HDMI CEC   : ${HDMI_CEC}"

  ${MAKEDEV} std
  ${MAKEDEV} fd
  ${MAKEDEV} hda hdb
  ${MAKEDEV} sda sdb sdc sdd
  ${MAKEDEV} scd0 scd1
  ${MAKEDEV} st0 st1
  ${MAKEDEV} sg
  ${MAKEDEV} ptyp ptyq
  ${MAKEDEV} console
  ${MAKEDEV} ttyAS0 ttyAS1 ttyAS2 ttyAS3
  ${MAKEDEV} lp par audio video fb rtc lirc st200 alsasnd
  ${MAKEDEV} ppp busmice
  ${MAKEDEV} input
  ${MAKEDEV} tundev
  ln -s -f /dev/input/mouse0 mouse
  ${MAKEDEV} i2c mtd

  ${MAKEDEV} dvb
  if [ ${CI} == "Yes" ]; then
    ${MAKEDEV} dvb_ci
    ${MAKEDEV} dvb_ca
  else
    ${MAKEDEV} dvb_ca_no
  fi
  if [ ${TUNER} == "2" ] || [ ${TUNER} == "3" ]; then
    ${MAKEDEV} dvb_2nd
    if [ ${CI} == "Yes" ]; then
      ${MAKEDEV} dvb_ca_2nd
    else
      ${MAKEDEV} dvb_ca_2nd_no
    fi
  fi
  if [ ${TUNER} == "3" ]; then
    ${MAKEDEV} dvb_3rd
    if [ ${CI} == "Yes" ]; then
      ${MAKEDEV} dvb_ca_3rd
    else
      ${MAKEDEV} dvb_ca_3rd_no
    fi
  fi

  ${MAKEDEV} mme bpamem
  ${MAKEDEV} vfd
  ${MAKEDEV} rc
  ${MAKEDEV} hdmi
  if [ ${HDMI_CEC} == "Yes" ]; then
    ${MAKEDEV} hdmi_cec
  fi
  ${MAKEDEV} ttyusb
  ${MAKEDEV} rfkill

  if [ "${HOST}" == "fortis" ]; then
    ${MAKEDEV} sci_fortis
  else
    ${MAKEDEV} sci
  fi

  ##rm -rf pts
  mkdir pts
  ##chown root.root pts
  ##chmod 0755 pts
  ##rm -rf shm
  mkdir shm
  ##chown root.root shm
  ##chmod 0755 shm

  touch .devfsd

  # Additional box specific stuff
  for TARGET in spark spark7162; do
    if [ ${HOST} == ${TARGET} ]; then
      ${MAKEDEV} uinput
      break
    fi
  done

  echo "[makedev] done."
}

case "$1" in
  start)
    start
    ;;
  *)
    echo $"Usage: $0 {start}"
    RETVAL=0
esac
